### 1. 정수 0으로 구성된 크기의 10의 벡터를 만드시오.

In [1]:
import numpy as np

In [3]:
z = np.zeros(10, dtype = int)

In [4]:
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### 2. 1에서 만든 배열의 총 바이트 크기를 구하는 코드를 작성해 보시오.

In [5]:
z.nbytes

40

### 3. 1에서 만든 배열에서 5번째 값을 1로 변경해 보시오.

In [6]:
z[4] = 1
z

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

### 4. 10~49까지의 정수 값을 연속적으로 가지는 벡터를 만들어 보시오.

In [8]:
x = np.arange(10, 50)

In [9]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 5. 4번에서 생성한 벡터를 역순으로 출력하는 코드를 작성하시오.

In [11]:
np.sort(x)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [48]:
x[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### 6. 0에서 8까지의 값을 가지는 1차원 배열을 3 * 3(2차원)배열로 바꿔보시오.

In [13]:
y = np.arange(0, 9).reshape(3, 3)

In [14]:
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 7. [1,2,0,0,4,0]에서 0이 아닌 원소의 위치를 저장한 배열을 만들어 보시오. (array[0,1,4]가 출력되도록 합니다.)

In [18]:
a = [1,2,0,0,4,0]
a1 = np.array(a)

In [25]:
a2 = []
for n in range(0, 6):
    if a1[n] != 0:
        a2.append(n)

In [26]:
a2

[0, 1, 4]

In [50]:
a = [1,2,0,0,4,0]
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

### 8. 랜덤값을 갖는 3 * 3 * 3 배열을 생성 하시오.

In [16]:
r = np.random.random((3, 3, 3))

In [17]:
r

array([[[0.75102629, 0.07829659, 0.36789159],
        [0.87456633, 0.92186494, 0.1869487 ],
        [0.16935987, 0.94389716, 0.673767  ]],

       [[0.32131958, 0.63206241, 0.74983061],
        [0.72717626, 0.08427118, 0.68870857],
        [0.99983075, 0.94968561, 0.65161534]],

       [[0.14142323, 0.08373309, 0.74964908],
        [0.48364578, 0.04866636, 0.22222952],
        [0.12509087, 0.85439775, 0.9838841 ]]])

### 9. 랜덤하게 생성된 10 * 10 배열의 최대, 최소 값을 찾아 출력하시오.

In [27]:
R = np.random.random((10, 10))

In [28]:
R

array([[2.70744534e-03, 7.90620445e-01, 5.36489681e-01, 8.77745528e-01,
        8.37225574e-01, 2.67936341e-01, 1.61824717e-01, 1.29777919e-01,
        5.95946515e-02, 5.86211612e-01],
       [8.70821125e-01, 7.83559069e-01, 2.03927582e-01, 3.70602594e-01,
        4.69544762e-01, 3.95324711e-01, 1.67975844e-04, 8.88545341e-01,
        4.80229829e-01, 4.08535008e-01],
       [9.05948375e-01, 3.43067431e-01, 4.66828612e-01, 5.69373091e-01,
        3.68095380e-01, 7.78093208e-01, 8.85477029e-02, 9.47094109e-01,
        6.31219878e-01, 6.27507540e-01],
       [6.79294422e-01, 3.37358838e-01, 6.54017903e-01, 1.10339628e-01,
        8.11257795e-01, 1.84257438e-01, 2.93266608e-01, 1.41545027e-02,
        4.37324885e-01, 4.41515133e-01],
       [3.80236568e-01, 1.56041391e-01, 7.94432482e-02, 5.97171664e-01,
        2.42825380e-01, 4.63498364e-01, 6.92781026e-01, 1.02616698e-01,
        3.03688816e-01, 5.47700155e-01],
       [3.51988105e-01, 1.44229808e-01, 8.37924169e-02, 9.25539195e-01,
   

In [30]:
np.max(R)

0.990131947872776

In [31]:
np.min(R)

0.00016797584358696493

In [51]:
R.max()

0.990131947872776

In [52]:
R.min()

0.00016797584358696493

### 10. 30개의 랜덤한 정수값을 갖는 배열을 생성하고, 모든 값의 평균을 출력하시오.

In [59]:
rr = np.random.randint(1, 10, 30)
rr

array([9, 9, 8, 7, 7, 2, 8, 4, 8, 3, 2, 5, 5, 3, 3, 9, 5, 9, 7, 4, 4, 3,
       4, 5, 7, 9, 5, 4, 9, 9])

In [60]:
np.mean(rr)

5.866666666666666

### 11. 10 * 10 배열을 가장 외곽은 모두 1, 안쪽은 모두 0으로 채워지도록 생성하시오.

In [66]:
z = np.ones((10, 10))

In [67]:
z[1:-1, 1:-1] = 0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### 12. 11과 반대로 외곽은 0, 안쪽을 모두 1이 채워지도록 하시오.

In [68]:
x = np.zeros((10, 10))

In [70]:
x[1:-1, 1:-1] = 1
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### 13. 8 * 8 배열에서 홀수 열은 0, 1 순으로, 짝수열은 1, 0 순으로 반복되도록 채우시오.

In [71]:
y = np.zeros((8, 8))
y[1::2, ::2] = 1
y

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [72]:
y[::2, 1::2] = 1
y

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

### 14. 정규분포를 따르는 5 * 5 배열의 랜덤 값을 생성하시오.

In [73]:
mean = 0  # 평균
std = 1  # 편차
np.random.normal(mean, std, (5, 5))

array([[-1.10883756,  1.43362393,  1.90595473,  1.96078831,  1.30804389],
       [ 0.17819556, -1.65902449,  1.90446595, -0.10793044, -0.75593996],
       [ 0.75483249,  2.25205041,  0.36655011,  0.92748841,  1.33598729],
       [-0.23993971, -0.54366898, -0.74766937, -2.36105947, -0.9829986 ],
       [-1.49506373, -0.6008232 , -0.30732441, -0.75130171,  0.32596023]])

### 15. 0에서 10까지의 10개의 데이터를 1차원 배열에 생성하고, 4~7만 음수로 바꾸는 코드를 작성하시오. 

In [74]:
a = np.arange(0, 11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
a[4:8]*=(-1)
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

### 16. 랜덤하게 생성된 10개의 값에서 가장 큰 값을 0으로 채우시오.

In [77]:
b = np.random.random(10)
b

array([0.14688456, 0.27047361, 0.53627316, 0.06112786, 0.38559813,
       0.40485161, 0.16519581, 0.43901597, 0.74369033, 0.05740591])

In [80]:
b[b.argmax()] = 0
b

array([0.14688456, 0.27047361, 0.53627316, 0.06112786, 0.38559813,
       0.40485161, 0.16519581, 0.43901597, 0.        , 0.05740591])

### 17. 다음 2차원 배열을 생성하고, 아래1), 2), 3)과 같이 출력하라

In [83]:
### 1) array([[5,6,7,8,9],
###           [0,1,2,3,4]])
### 2) array([[4,3,2,1,0],
###           [9,8,7,6,5]])
### 3) array([[9,8,7,6,5],
###           [4,3,2,1,0]])

In [84]:
import numpy as np
arr_2d = np.arange(10).reshape(2,5)
arr_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [91]:
z = arr_2d[::-1]

In [92]:
z

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [94]:
z1 = z[::-1, ::-1]
z1

array([[4, 3, 2, 1, 0],
       [9, 8, 7, 6, 5]])

In [95]:
z1[::-1]

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])

In [96]:
z[::1, ::-1]

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])

In [97]:
arr_2d[::-1][::-1, ::-1]

array([[4, 3, 2, 1, 0],
       [9, 8, 7, 6, 5]])

In [98]:
arr_2d[:, ::-1]

array([[4, 3, 2, 1, 0],
       [9, 8, 7, 6, 5]])

In [99]:
arr_2d[::1, ::-1]

array([[4, 3, 2, 1, 0],
       [9, 8, 7, 6, 5]])